#!/usr/bin/python3
"""
Factorize a given set of numbers in a file into products of two small numbers.
"""

import sys

def factorize(number_to_check):
    """
    Find two small numbers that multiply to give a given number.
    """
    if number_to_check < 2:
        return

    i = 2
    while number_to_check % i:
        i += 1

    print("{:.0f} = {:.0f} * {:.0f}".format(number_to_check, number_to_check / i, i))

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <filename>".format(sys.argv[0]))
        sys.exit(1)

    try:
        with open(sys.argv[1], 'r') as file:
            for line in file:
                number_to_check = int(line.strip())
                factorize(number_to_check)

    except FileNotFoundError:
        print("Error: File '{}' not found.".format(sys.argv[1]))
        sys.exit(1)

    except ValueError:
        print("Error: Invalid input in the file.")
        sys.exit(1)

if __name__ == "__main__":
    main()

